@startuml VendaProdutos

top to bottom direction

package Apresentacao {
    class Controller {
    }
}

package Negocio {
}

package Persistencia {
}

Apresentacao -[hidden]-> Negocio
Negocio -[hidden]-> Persistencia

@enduml
